### ISSUE TITLE
smooth quartz stair missing texture...I guess

### ISSUE THREAD

**Issue by Maelcat** [jasonjgardner/jg-rtx#1]
I want to think that this was pretty much intentional _(just like the cat block lol)_
but if that's not the case then yep, the block is missing the texture
![Minecraft Screenshot 2020 08 04 - 00 34 09 32](https://user-images.githubusercontent.com/53267697/89256889-b68d5280-d5ea-11ea-9685-1e3792c4223f.png)

**Comment by jasonjgardner** [comment]
Thanks for your input! Taking it out was intentional, but leaving it out was not. The `smooth_quartz_stairs` block was assigned to the texture `stair_smooth_quartz_block`, which doesn't exist/isn't used in Minecraft 1.15. I must have copied [block.json](../commits/master/dist/blocks.json) data from a later Minecraft version. The texture appears correctly now. It's not a texture I have customized yet, so you'll still see the fallback texture in the game.

---
I have the vanilla resource packs from [aka.ms/resourcepacktemplate](https://aka.ms/resourcepacktemplate) for versions 1.14 and 1.16, but not for 1.15. **If anyone still has the vanilla resource pack template for Minecraft 1.15, please share it!**
