### ISSUE TITLE
The grass_top_normal.png texture in 0.10.0 looks odd when rotated, and other things

### ISSUE THREAD

**Issue by erich666** [jasonjgardner/jg-rtx#6]
**Wha happen?**

The grass_top_normal.png texture in 0.8.0 is OK. A little odd looking, perhaps, but it's "rotation invariant." Minecraft normally randomly rotates the grass tops so that they don't show an obvious repeating pattern. If you apply normal maps to these grass tops, I think the normals need to be "unbiased", that is, on average the normals should face up. In 0.10.0 this texture seems to have a definite directional bias, which can be seen when rendering:

![image](https://user-images.githubusercontent.com/803995/106319035-d4a4da00-623e-11eb-88d3-36592f1c1f63.png)

The normal map in 0.8.0 looks fine:

![image](https://user-images.githubusercontent.com/803995/106319234-20f01a00-623f-11eb-8ff2-c9947af2af84.png)

Here's the old normal map compared to the new one:

![image](https://user-images.githubusercontent.com/803995/106319314-3ebd7f00-623f-11eb-900f-532e22842802.png)

I can't say I know why these display so differently, but there's a definite problem here, one I don't see with most other resource packs that provide normals for grass.

Some other textures that could perhaps use a little love, unless they're purposely this way for some reason:
* cakes are emissive on some surfaces - bottom, inner, side - and quite different from each other. That seems odd. There's no top MER texture.
* trip_wire_source_mer.png has emissive value for the ring.
* damaged anvil tops are oddly colored and emissive, with little 4x4 patterns on them.

**Comment by jasonjgardner** [comment]
I mistakenly left the grass material's normal map channel disabled in Substance Painter. The earlier grass version's normal map shows the ground material's normal map. In the 0.10.0-alpha release, the grass material was "fixed" so that the blades of grass appeared in the normal map output; however, this grass material is probably better suited for higher-resolution textures...

I've created new grass, dirt, and path textures to include in the next release. Here are a few screenshots and a much more tame-looking normal map:

> ![grass_carried_normal](https://user-images.githubusercontent.com/1903667/106658282-b6065200-6562-11eb-8178-fa0206459ed9.png)
> New `grass_top` normal map

> ![Grass screenshot](https://user-images.githubusercontent.com/1903667/106659233-0f22b580-6564-11eb-8181-ccac52b066d9.png)
> Grass field

> ![Dirt screenshot](https://user-images.githubusercontent.com/1903667/106658810-696f4680-6563-11eb-8fa4-b8dbf6d9507d.png)
> New dirt, grass sides, and stone

> ![Grass screenshot](https://user-images.githubusercontent.com/1903667/106659005-c10db200-6563-11eb-8036-9bbae1bb05e0.png)
> Grass side closer

> ![Grass screenshot](https://user-images.githubusercontent.com/1903667/106658927-9a4f7b80-6563-11eb-82d5-279aa55e8a08.png)
> Grass top and sides in daylight

> ![Grass path screenshot](https://user-images.githubusercontent.com/1903667/106659171-f7e3c800-6563-11eb-905b-aada952bed1e.png)
> Grass and path textures

> ![Grass texture rotation screenshot](https://user-images.githubusercontent.com/1903667/106659317-3083a180-6564-11eb-9c3a-9a6fee29fcbc.png)
> Arbitrary texture rotation example

Maybe not perfect but certainly an improvement, I think. Feedback welcome.

---

As for cakes, tripwire hooks, and anvils: Those were intentionally given unique, emissive textures. These are just conceptual/experimental textures I'm playing with while in development.

You might have also noticed the mushroom skin interior textures are emissive and the stems and exterior are metallic. This was by design. The purple lighting is supposed to be similar to blacklights. The metal exterior is supposed to make them appear like some kind of giant sculpture (and it reflects the interior lighting nicely). Swamps and mushroom biomes look pretty neat. Plus, these blocks can be repurposed several ways in Creative mode.

It's brilliant, I tell you.

**Comment by erich666** [comment]
> It's brilliant, I tell you.

lol. Yeah, I try not to ask too many questions... I've also seen packs with glowing trapdoors (used as lights), concrete, wither roses, and whatnot. Now I want to go visit a swamp.

Anyway, confirmed: the new normals texture looks great - bug's gone. Good deal.

![image](https://user-images.githubusercontent.com/803995/106665856-d5a67600-6574-11eb-9a48-2ad4653b9edb.png)
