### ISSUE TITLE
funky furnace

### ISSUE THREAD

**Issue by ILUVHINATA** [jasonjgardner/jg-rtx#9]
is there supposed to be a furnace front on png?
if there is......there isn't...

got black and pink front furnaces when i cook shit. pls fix.
when i load back into the main menu with the stuff loaded, i see a black and pink loading screen too, these issues didn't exist the other day when i downloaded the updates. what happened?

**Comment by jasonjgardner** [comment]
The furnace texture is still in the works. I'll fix it as soon as I can! I haven't experienced that bug myself but I'll try to recreate it. Either way, adding another texture for the furnace ought to solve it. Thanks for letting me know!

**Comment by ILUVHINATA** [comment]
not a problem, since i like this stuff, hopefully you finish this stuff with EVERYTHING improved, i like your work, and would like better textures for all items, chests, etc.. just don't modify the UI in any way, and i'm set, cuz i use this for my minecraft realm.

**Comment by jasonjgardner** [comment]
Thanks! I don't plan on modifying the UI, other than perhaps the main menu panorama. I do plan on adding entity textures, like chests, boats, and maybe some mobs. Unfortunately, [this Minecraft Help Center article](https://help.minecraft.net/hc/en-us/articles/360042255511-Minecraft-with-Ray-Tracing-Known-Issues-List) says:

> At this time there is no support for authoring PBR materials for entities, skins, or Character Creator items 

So I haven't made some entity textures a priority...

---

I'm closing this issue because a filler furnace texture was added in [this commit](https://github.com/jasonjgardner/jg-rtx/commit/bceb5031c947f0dd1ac40668e5523431f9fc1c0e)
